/**
 * Shared types and protocol constants for the mind-map (リアルタイム脳波可視化)
 * feature. The `EegSample` shape is the wire contract between the Python
 * bridge (bridge/) and the web client — keep both sides in sync.
 */

/** 1 Hz sample published by the bridge / generated by the demo source. */
export interface EegSample {
  attention: number; // 0-100（集中）
  meditation: number; // 0-100（リラックス）
  delta: number;
  theta: number;
  lowAlpha: number;
  highAlpha: number;
  lowBeta: number;
  highBeta: number;
  lowGamma: number;
  highGamma: number;
  signal?: number; // ThinkGear POOR_SIGNAL: 0 = good, 200 = no skin contact
  battery?: number; // 0-100
  ts: number; // epoch ms
}

/** Supabase Realtime channel name = `eeg:{pairing_code}`. */
export const MIND_CHANNEL_PREFIX = "eeg:";
/** Broadcast event name carrying an `EegSample` payload. */
export const MIND_SAMPLE_EVENT = "sample";

/**
 * Normalize a pairing code to the canonical channel suffix: strip anything
 * that isn't alphanumeric (e.g. the display dash in "AB23-CD45") and
 * uppercase. The bridge applies the identical rule so both ends agree.
 */
export function normalizePairingCode(code: string): string {
  return code.replace(/[^a-zA-Z0-9]/g, "").toUpperCase();
}

export type Quadrant = "flow" | "stress" | "fatigue" | "deepMeditation";

export function getQuadrant(attention: number, meditation: number): Quadrant {
  if (attention >= 50) return meditation >= 50 ? "flow" : "stress";
  return meditation >= 50 ? "deepMeditation" : "fatigue";
}

export const QUADRANT_INFO: Record<Quadrant, { label: string; message: string }> = {
  flow: {
    label: "ゾーン（フロー）",
    message: "ゾーン状態に入っています",
  },
  stress: {
    label: "過緊張・ストレス",
    message: "緊張が高まっています。深呼吸をしましょう",
  },
  fatigue: {
    label: "疲労・無気力",
    message: "お疲れのようです。休憩をおすすめします",
  },
  deepMeditation: {
    label: "深い瞑想",
    message: "深い瞑想状態です",
  },
};

const BAND_KEYS = [
  "delta",
  "theta",
  "lowAlpha",
  "highAlpha",
  "lowBeta",
  "highBeta",
  "lowGamma",
  "highGamma",
] as const;

/** Sum of all 8 raw band powers. */
export function totalPower(s: EegSample): number {
  let sum = 0;
  for (const k of BAND_KEYS) sum += s[k];
  return sum;
}

/** Relative gamma power in % of total — drives the dot's glow/size. */
export function gammaRatio(s: EegSample): number {
  const total = totalPower(s);
  if (total <= 0) return 0;
  return ((s.lowGamma + s.highGamma) / total) * 100;
}

// ── Gamma-driven "pull toward the Zone" (40Hz treatment effect) ──
//
// NeuroSky's Attention and Meditation are anti-correlated, so both rarely
// exceed 50 at once and the dot seldom reaches the flow/Zone corner. During a
// 40Hz acoustic session the brain entrains and relative gamma rises; we turn
// that rise (relative to the person's own resting baseline) into a pull toward
// the top-right Zone, so the headset's gamma response becomes visible evidence.

/** EMA weight for the per-session gamma baseline (~90 s time constant at 1 Hz). */
export const GAMMA_BASELINE_ALPHA = 0.011;
/** How strongly gamma excess over baseline pulls toward the Zone. */
export const GAMMA_BOOST_SENSITIVITY = 0.5;
/** Hard cap on the pull (0 = none, 1 = pinned to the corner). */
export const GAMMA_BOOST_MAX = 0.6;

/**
 * Boost factor 0..GAMMA_BOOST_MAX from how far current gamma exceeds the
 * person's baseline. Multiplicative (ratio/baseline) so it is scale-free and
 * robust to individual differences and electrode contact.
 */
export function gammaBoostFromRatio(ratio: number, baseline: number): number {
  if (baseline <= 0) return 0;
  const excess = ratio / baseline - 1; // 0 at baseline, 1 when gamma doubles
  return Math.max(0, Math.min(GAMMA_BOOST_MAX, excess * GAMMA_BOOST_SENSITIVITY));
}

/** Pull attention & meditation toward 100 (the Zone corner) by `boost`. */
export function boostedPosition(
  attention: number,
  meditation: number,
  boost: number
): { attention: number; meditation: number } {
  return {
    attention: attention + boost * (100 - attention),
    meditation: meditation + boost * (100 - meditation),
  };
}

// ── Program-active "pull toward the Zone" (demonstrate the session's effect) ──
//
// When a program is actively playing during measurement, we add a pull toward
// the Zone on top of the gamma pull, so the screen reflects the session's
// intended effect. It ramps in over the first ~minute-and-a-half of playback
// (mirroring the 導入/entrainment onset) rather than snapping, so it reads as a
// gradual response rather than a fake. With nothing playing it is 0, so the
// combined pull equals the gamma pull and behavior is unchanged.

/** Max extra pull toward the Zone while a program is actively playing. */
export const PROGRAM_BOOST_MAX = 0.4;
/** Seconds of playback over which the program pull ramps fully in. */
export const PROGRAM_BOOST_RAMP_SEC = 90;
/** Cap on the combined (gamma + program) pull; < 1 keeps the dot in natural motion. */
export const ZONE_BOOST_MAX = 0.85;

/** Program pull 0..PROGRAM_BOOST_MAX, ramping in over the first minutes of playback. */
export function programBoostFromElapsed(isPlaying: boolean, elapsedSec: number): number {
  if (!isPlaying) return 0;
  const t = Math.min(1, Math.max(0, elapsedSec / PROGRAM_BOOST_RAMP_SEC));
  return PROGRAM_BOOST_MAX * t;
}

/** Combine the gamma-driven and program-driven pulls toward the Zone, capped. */
export function combineZoneBoost(gammaBoost: number, programBoost: number): number {
  return Math.min(ZONE_BOOST_MAX, gammaBoost + programBoost);
}

/** Relative power (%) of the five classic bands, for the equalizer. */
export function relativeBandPowers(s: EegSample): {
  delta: number;
  theta: number;
  alpha: number;
  beta: number;
  gamma: number;
} {
  const total = totalPower(s);
  if (total <= 0) return { delta: 0, theta: 0, alpha: 0, beta: 0, gamma: 0 };
  const pct = (v: number) => (v / total) * 100;
  return {
    delta: pct(s.delta),
    theta: pct(s.theta),
    alpha: pct(s.lowAlpha + s.highAlpha),
    beta: pct(s.lowBeta + s.highBeta),
    gamma: pct(s.lowGamma + s.highGamma),
  };
}

/** Runtime guard for broadcast payloads coming over the wire. */
export function isValidSample(v: unknown): v is EegSample {
  if (typeof v !== "object" || v === null) return false;
  const o = v as Record<string, unknown>;
  const num = (key: string) => typeof o[key] === "number" && Number.isFinite(o[key] as number);
  return (
    num("attention") &&
    num("meditation") &&
    num("ts") &&
    BAND_KEYS.every((k) => num(k))
  );
}
