/**
 * Shared types and protocol constants for the mind-map (リアルタイム脳波可視化)
 * feature. The `EegSample` shape is the wire contract between the Python
 * bridge (bridge/) and the web client — keep both sides in sync.
 */

/** 1 Hz sample published by the bridge / generated by the demo source. */
export interface EegSample {
  attention: number; // 0-100（集中）
  meditation: number; // 0-100（リラックス）
  delta: number;
  theta: number;
  lowAlpha: number;
  highAlpha: number;
  lowBeta: number;
  highBeta: number;
  lowGamma: number;
  highGamma: number;
  signal?: number; // ThinkGear POOR_SIGNAL: 0 = good, 200 = no skin contact
  battery?: number; // 0-100
  ts: number; // epoch ms
}

/** Supabase Realtime channel name = `eeg:{supabase_user_id}`. */
export const MIND_CHANNEL_PREFIX = "eeg:";
/** Broadcast event name carrying an `EegSample` payload. */
export const MIND_SAMPLE_EVENT = "sample";

export type Quadrant = "flow" | "stress" | "fatigue" | "deepMeditation";

export function getQuadrant(attention: number, meditation: number): Quadrant {
  if (attention >= 50) return meditation >= 50 ? "flow" : "stress";
  return meditation >= 50 ? "deepMeditation" : "fatigue";
}

export const QUADRANT_INFO: Record<
  Quadrant,
  { label: string; message: string; color: string }
> = {
  flow: {
    label: "ゾーン（フロー）",
    message: "ゾーン状態に入っています",
    color: "#e8b84a",
  },
  stress: {
    label: "過緊張・ストレス",
    message: "緊張が高まっています。深呼吸をしましょう",
    color: "#d4604a",
  },
  fatigue: {
    label: "疲労・無気力",
    message: "お疲れのようです。休憩をおすすめします",
    color: "#5a6478",
  },
  deepMeditation: {
    label: "深い瞑想",
    message: "深い瞑想状態です",
    color: "#3a5fd4",
  },
};

const BAND_KEYS = [
  "delta",
  "theta",
  "lowAlpha",
  "highAlpha",
  "lowBeta",
  "highBeta",
  "lowGamma",
  "highGamma",
] as const;

/** Sum of all 8 raw band powers. */
export function totalPower(s: EegSample): number {
  let sum = 0;
  for (const k of BAND_KEYS) sum += s[k];
  return sum;
}

/** Relative gamma power in % of total — drives the dot's glow/size. */
export function gammaRatio(s: EegSample): number {
  const total = totalPower(s);
  if (total <= 0) return 0;
  return ((s.lowGamma + s.highGamma) / total) * 100;
}

/** Relative power (%) of the five classic bands, for the equalizer. */
export function relativeBandPowers(s: EegSample): {
  delta: number;
  theta: number;
  alpha: number;
  beta: number;
  gamma: number;
} {
  const total = totalPower(s);
  if (total <= 0) return { delta: 0, theta: 0, alpha: 0, beta: 0, gamma: 0 };
  const pct = (v: number) => (v / total) * 100;
  return {
    delta: pct(s.delta),
    theta: pct(s.theta),
    alpha: pct(s.lowAlpha + s.highAlpha),
    beta: pct(s.lowBeta + s.highBeta),
    gamma: pct(s.lowGamma + s.highGamma),
  };
}

/** Runtime guard for broadcast payloads coming over the wire. */
export function isValidSample(v: unknown): v is EegSample {
  if (typeof v !== "object" || v === null) return false;
  const o = v as Record<string, unknown>;
  const num = (key: string) => typeof o[key] === "number" && Number.isFinite(o[key] as number);
  return (
    num("attention") &&
    num("meditation") &&
    num("ts") &&
    BAND_KEYS.every((k) => num(k))
  );
}
