// @generated by scripts/import-program-xlsx.mjs — 直接編集しない
// 取り込み元: （まだ取り込んでいない）
import type { CatalogParams } from "./factory";

/**
 * 一覧 xlsx から取り込んだ確定パラメータ。ここに id が載っている節目は
 * paramsProvisional が外れる。名前・よみ・アイコン・並び順は
 * lib/catalog/{target,energy}.ts 側が持ち、この生成物では触らない。
 *
 * いまは空＝全件が暫定値。一覧 xlsx を入手したら
 *   node scripts/import-program-xlsx.mjs --inspect <file.xlsx>
 *   node scripts/import-program-xlsx.mjs --in <file.xlsx>
 * の順で走らせると、ここが埋まる。
 */
export const CATALOG_PARAMS: Readonly<Record<string, CatalogParams>> = {};
